const courseData = [
  {
    id: 1,
    category: "Web Vulnerabilities",
    title: "SQL Injection",
    description:
      "Learn how attackers exploit vulnerabilities in web applications using SQL injection and understand the techniques to detect and prevent them.",
    topics: [
      "Retrieving hidden data",
      "SQL injection UNION attacks",
      "Finding columns with a useful data type",
      "Using a SQL injection UNION attack to retrieve interesting data",
    ],
    difficulty: "Easy",
    image: require("../assets/img/SQL_Injection/landing3.png"),
    link: "/sql_Injection",
  },
  {
    id: 2,
    category: "Web Vulnerabilities",
    title: "Cross-Site Scripting",
    description:
      "Learn the fundamentals of Cross-Site Scripting (XSS), one of the most common vulnerabilities in web applications.",
    topics: [
      "What is Cross-Site Scripting?",
      "Types of XSS",
      "Exploitation Techniques",
      "Mitigation Strategies",
    ],
    difficulty: "Easy",
    image: require("../assets/img/Cross_Site_Scripting/xss.jpeg.jpg"),
    link: "/xss",
  },
  {
    id: 3,
    category: "Web Vulnerabilities",
    title: "Cookies",
    description:
      "Understand the role of cookies in web security, how they are used, and the potential privacy concerns they introduce.",
    topics: [
      "What Are Cookies?",
      "What are Cookies Used For?",
      "Where are Cookies Stored?",
      "Cookies Manipulation",
    ],
    difficulty: "Easy",
    image: require("../assets/img/cookies/Cookies_transparent.png"),
    link: "/cookies",
  },
  {
    id: 4,
    category: "Web Vulnerabilities",
    title: "Access Control Vulnerabilities",
    description:
      "Learn how attackers exploit vulnerabilities in web applications to bypass access controls and understand the techniques to detect and prevent them.",
    topics: [
      "What are Access Control Vulnerabilities?",
      "Types of Access Control Flaws",
      "Exploitation Examples",
      "Mitigation Techniques",
    ],
    difficulty: "Easy",
    image: require("../assets/img/ACV/landing.jpeg"),
    link: "/AC_Vuln",
  },
  {
    id: 5,
    category: "Server-Side Exploits",
    title: "Unrestricted File Upload",
    description:
      "Understand the risks and exploitation of unrestricted file upload vulnerabilities, a critical security issue in web applications.",
    topics: [
      "What is Unrestricted File Upload?",
      "Why is it Dangerous?",
      "Attack Techniques",
      "Exploitation Scenarios",
    ],
    difficulty: "Easy",
    image: require("../assets/img/Unrestricted File Upload/card_image.png"),
    link: "/UnrestrictedFileUpload",
  },
  {
    id: 6,
    category: "Fundamentals",
    title: "Linux Fundamentals",
    description:
      "Build a solid foundation in Linux, the operating system at the core of many cybersecurity tools and infrastructures.",
    topics: [
      "Running Your First Few Commands",
      "Interacting with the Filesystem",
      "Searching for Files",
      "Introduction to Shell Operators",
    ],
    difficulty: "Easy",
    image: require("../assets/img/linux/linux_logo.png"),
    link: "/linux",
  },
  {
    id: 7,
    category: "Web Vulnerabilities",
    title: "Business Logic Vulnerabilities",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Easy",
    image: require("../assets/img/BLV/landing.avif"),
    link: "/BL_Vuln",
  },
  {
    id: 8,
    category: "Web Vulnerabilities",
    title: "Broken Authentication",
    description:
      "Learn the core skills required to start a career in cyber security",
    topics: [
      "Learn about different careers in cyber",
      "Hack your first application",
      "Defend against a live cyber attack",
      "Explore security topics in the industry",
    ],
    difficulty: "Easy",
    image: require("../assets/img/Broken Authentication/card_image.png"),
    link: "/broken-auth",
  },
  {
    id: 9,
    category: "Server-Side Exploits",
    title: "Bash Scripting",
    description:
      " Master the basics of Bash scripting, a powerful tool for automating tasks and managing systems in cybersecurity environments.",
    topics: ["simple bash scripts", "Variables", "Parameters", "Arrays"],
    difficulty: "Easy",
    image: require("../assets/img/bash/bash_course_logo.png"),
    link: "/bash-scripting",
  },
  {
    id: 10,
    category: "Fundamentals",
    title: "Cross Site Request Forgery (CSRF)",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Easy",
    image: require("../assets/img/CSRF/landing.jpg"),
    link: "/CSRF",
  },
  {
    id: 11,
    category: "Specialized Topics",
    title: "Insecure Direct Object Reference(IDOR)",
    description:
      "Delve into Insecure Direct Object Reference (IDOR) vulnerabilities, a common security issue in web applications. Learn how attackers exploit weak access controls to gain unauthorized access to sensitive resources.",
    topics: [
      "What is IDOR?",
      "Why is it Dangerous?",
      "Common Examples.",
      "Exploitation Techniques.",
      "Mitigation Strategies.",
    ],
    difficulty: "Easy",
    image: require("../assets/img/IDOR/Insecure_Direct_Object_Reference.png"),
    link: "/Insecure_Direct_Object_Reference(IDOR)",
  },
  {
    id: 12,
    category: "Specialized Topics",
    title: "Obfuscation",
    description:
      "Master the basics of obfuscation, a powerful technique for securing code and protecting intellectual property in cybersecurity environments",
    topics: [
      "What are Obfuscation & Deobfuscation?",
      "Why do we use Obfuscation?",
      "Javascript Obfuscation",
      "JS Deobfuscation Tools",
    ],
    difficulty: "Easy",
    image: require("../assets/img/Obfuscation/card_image.png"),
    link: "/obfuscation",
  },
  {
    id: 13,
    category: "Specialized Topics",
    title: "Regular expressions",
    description:
      " Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Easy",
    image: require("../assets/img/Regex/landing.jpeg"),
    link: "/Regex",
  },
  {
    id: 14,
    category: "Temporary Category",
    title: "Temporary Topic",
    description:
      "This is a temporary placeholder topic to meet the required number of 30 topics.",
    topics: [
      "Placeholder Topic 1",
      "Placeholder Topic 2",
      "Placeholder Topic 3",
      "Placeholder Topic 4",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Lab2.jpg"),
    link: "/Path__Traversal",
  },
  {
    id: 15,
    category: "Temporary Category",
    title: "Cryptography",
    description:
      "Master the basics of CryptoGraphy, a powerful technique for securing code and protecting intellectual property in cybersecurity environments.",
    topics: [
      "What is Cryptography?",
      "What is Steganography?",
      "How does Steganography differ from Cryptography?",
      "Types of Encryption",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Cryptography/card_image.png"),
    link: "/cryptography",
  },
  {
    id: 16,
    category: "Temporary Category",
    title: "Hashing",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/InfoDisc/landing.jpg"),
    link: "/Hashing",
  },
  {
    id: 17,
    category: "Temporary Category",
    title: "Burp Suite",
    description:
      " Learn the core skills required to start a career in cyber security",
    topics: [
      "Learn about different careers in cyber",
      "Hack your first application",
      "Defend against a live cyber attack",
      "Explore security topics in the industry",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Lab2.jpg"),
    link: "/lab2",
  },
  {
    id: 18,
    category: "Temporary Category",
    title: "wireshark",
    description:
      "Master the Fundamentals of Wireshark: A Powerful Tool for Cybersecurity and Code Protection",
    topics: [
      "Wireshark Overview",
      "Collection Methods",
      "ARP Traffic",
      "ICMP & TCP Traffic",
    ],
    difficulty: "Medium",
    image: require("../assets/img/wireshark/card_image.png"),
    link: "/wireshark",
  },
  {
    id: 19,
    category: "Temporary Category",
    title: "Digital Forensics✅",
    description:
      " Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/AudFor/landing.png"),
    link: "/Digital_Forensics",
  },
  {
    id: 20,
    category: "Temporary Category",
    title: "Command Injection",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Lab2.jpg"),
    link: "/infoDisc",
  },
  {
    id: 21,
    category: "Temporary Category",
    title: "File Inclusion",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/File Inclusion/card_image.png"),
    link: "/fileinclusion",
  },
  {
    id: 22,
    category: "Temporary Category",
    title: "Path Traversal",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Path_Traversal/landing.jpeg"),
    link: "/Path_Traversal",
  },
  {
    id: 23,
    category: "Temporary Category",
    title: "Insecure Deserialization",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Lab2.jpg"),
    link: "/infoDisc",
  },
  {
    id: 24,
    category: "Temporary Category",
    title: "Server Side Template Injection (SSTI)",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Server Side Template Injection/card_image.png"),
    link: "/SSTI",
  },
  {
    id: 25,
    category: "Temporary Category",
    title: "API Hacking & Testing",
    description:
      " Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Api_Hacking/landing.png"),
    link: "/Api_Hacking",
  },
  {
    id: 26,
    category: "Temporary Category",
    title: "?????",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Lab2.jpg"),
    link: "/infoDisc",
  },
  {
    id: 27,
    category: "Temporary Category",
    title: "Captcha Bypass",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Captcha Bypass/card_image.png"),
    link: "/captchabypass",
  },
  {
    id: 28,
    category: "Temporary Category",
    title: "click jacking",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Click_Jacking/landing.jpeg"),
    link: "/Click_Jacking",
  },
  {
    id: 29,
    category: "Temporary Category",
    title: "29.",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Lab2.jpg"),
    link: "/infoDisc",
  },
  {
    id: 30,
    category: "Temporary Category",
    title: "JWT attacks",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/JWT attacks/card_image.png"),
    link: "/jwtattacks",
  },
];

export default courseData;
