const courseData = [
  {
    id: 1,
    category: "Career & Industry",
    title: "Careers in Cyber",
    description:
      "Explore various career paths in the cybersecurity industry and learn about required skills and opportunities.",
    topics: [
      "Overview of Cyber Careers",
      "Educational Paths",
      "Industry Certifications",
      "Job Market Trends",
    ],
    difficulty: "Beginner",
    image: require("../assets/img/CareersInCyber/landing.jpg"),
    state: "pending",
    link: "/CareersInCyber",
  },
  {
    id: 2,
    category: "Tools & Techniques",
    title: "Burp Suite",
    description:
      "Learn the core skills required to start a career in cyber security",
    topics: [
      "Learn about different careers in cyber",
      "Hack your first application",
      "Defend against a live cyber attack",
      "Explore security topics in the industry",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/Burp_Suit/BurpSuit_Content.png"),
    state: "not-published",
    link: "/Burp_Suit",
  },
  {
    id: 3,
    category: "Fundamentals",
    title: "Cookies",
    description:
      "Understand the role of cookies in web security, how they are used, and the potential privacy concerns they introduce.",
    topics: [
      "What Are Cookies?",
      "What are Cookies Used For?",
      "Where are Cookies Stored?",
      "Cookies Manipulation",
    ],
    difficulty: "Beginner",
    image: require("../assets/img/cookies/Cookies_transparent.png"),
    state: "published",
    link: "/cookies",
  },
  {
    id: 4,
    category: "Vulnerabilities",
    title: "SQL Injection",
    description:
      "Learn how attackers exploit vulnerabilities in web applications using SQL injection and understand the techniques to detect and prevent them.",
    topics: [
      "Retrieving hidden data",
      "SQL injection UNION attacks",
      "Finding columns with a useful data type",
      "Using a SQL injection UNION attack to retrieve interesting data",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/SQL_Injection/landing3.png"),
    state: "semi-published",
    link: "/sql_Injection",
  },
  {
    id: 5,
    category: "Vulnerabilities",
    title: "Unrestricted File Upload",
    description:
      "Understand the risks and exploitation of unrestricted file upload vulnerabilities, a critical security issue in web applications.",
    topics: [
      "What is Unrestricted File Upload?",
      "Why is it Dangerous?",
      "Attack Techniques",
      "Exploitation Scenarios",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/Unrestricted File Upload/card_image.png"),
    state: "published",
    link: "/UnrestrictedFileUpload",
  },
  {
    id: 6,
    category: "Fundamentals",
    title: "Linux Fundamentals",
    description:
      "Build a solid foundation in Linux, the operating system at the core of many cybersecurity tools and infrastructures.",
    topics: [
      "Running Your First Few Commands",
      "Interacting with the Filesystem",
      "Searching for Files",
      "Introduction to Shell Operators",
    ],
    difficulty: "Beginner",
    image: require("../assets/img/linux/linux_logo.png"),
    state: "published",
    link: "/linux",
  },
  {
    id: 7,
    category: "Vulnerabilities",
    title: "Access Control Vulnerabilities",
    description:
      "Learn how attackers exploit vulnerabilities in web applications to bypass access controls and understand the techniques to detect and prevent them.",
    topics: [
      "What are Access Control Vulnerabilities?",
      "Types of Access Control Flaws",
      "Exploitation Examples",
      "Mitigation Techniques",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/ACV/Landing.jpg"),
    state: "semi-published",
    link: "/AC_Vuln",
  },
  {
    id: 8,
    category: "Vulnerabilities",
    title: "Broken Authentication",
    description:
      "Broken authentication lets attackers impersonate users, leading to account takeovers and data breaches. Securing login and session management helps prevent these risks.",
    topics: [
      "Weak Passwords",
      "Session Management Issues",
      "Lack of MFA",
      "Credential Stuffing",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/Broken Authentication/card_image.png"),
    state: "published",
    link: "/broken-auth",
  },
  {
    id: 9,
    category: "Fundamentals",
    title: "Bash Scripting",
    description:
      "Master the basics of Bash scripting, a powerful tool for automating tasks and managing systems in cybersecurity environments.",
    topics: ["simple bash scripts", "Variables", "Parameters", "Arrays"],
    difficulty: "Beginner",
    image: require("../assets/img/bash/bash_course_logo.png"),
    state: "published",
    link: "/bash-scripting",
  },
  {
    id: 10,
    category: "Vulnerabilities",
    title: "Business Logic Vulnerabilities",
    description:
      "Explore how flaws in business logic can be exploited by attackers and learn mitigation strategies.",
    topics: [
      "Understanding Business Logic",
      "Identifying Flaws",
      "Exploitation Techniques",
      "Mitigation Strategies",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/BLV/Landing.jpg"),
    state: "not-published",
    link: "/BL_Vuln",
  },
  {
    id: 11,
    category: "Vulnerabilities",
    title: "Insecure Direct Object Reference(IDOR)",
    description:
      "Delve into Insecure Direct Object Reference (IDOR) vulnerabilities, a common security issue in web applications. Learn how attackers exploit weak access controls to gain unauthorized access to sensitive resources.",
    topics: [
      "What is IDOR?",
      "Why is it Dangerous?",
      "Common Examples",
      "Exploitation Techniques",
      "Mitigation Strategies",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/IDOR/Insecure_Direct_Object_Reference.png"),
    state: "published",
    link: "/Insecure_Direct_Object_Reference(IDOR)",
  },
  {
    id: 12,
    category: "Tools & Techniques",
    title: "Obfuscation",
    description:
      "Master the basics of obfuscation, a powerful technique for securing code and protecting intellectual property in cybersecurity environments.",
    topics: [
      "What are Obfuscation & Deobfuscation?",
      "Why do we use Obfuscation?",
      "Javascript Obfuscation",
      "JS Deobfuscation Tools",
    ],
    difficulty: "Beginner",
    image: require("../assets/img/Obfuscation/card_image.png"),
    state: "published",
    link: "/obfuscation",
  },
  {
    id: 13,
    category: "Vulnerabilities",
    title: "Cross Site Request Forgery (CSRF)",
    description:
      "Learn how CSRF attacks exploit user trust and how to secure applications against them.",
    topics: [
      "Understanding CSRF",
      "Exploitation Methods",
      "Prevention Techniques",
      "Real-world Examples",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/CSRF/landing.jpg"),
    state: "semi-published",
    link: "/CSRF",
  },
  {
    id: 14,
    category: "Vulnerabilities",
    title: "Path Traversal",
    description:
      "Exploiting file path vulnerabilities to access restricted directories and files.",
    topics: [
      "Path traversal techniques",
      "Directory traversal prevention",
      "Secure file access mechanisms",
      "Case Studies",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/Path__Traversal/Photo_Content_Path_Traversal.png"),
    state: "published",
    link: "/Path__Traversal",
  },
  {
    id: 15,
    category: "Fundamentals",
    title: "Cryptography",
    description:
      "Master the basics of Cryptography, a powerful technique for securing data and communications in cybersecurity environments.",
    topics: [
      "What is Cryptography?",
      "What is Steganography?",
      "How does Steganography differ from Cryptography?",
      "Types of Encryption",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/Cryptography/card_image.png"),
    state: "published",
    link: "/cryptography",
  },
  {
    id: 16,
    category: "Fundamentals",
    title: "Regular expressions",
    description:
      "Learn how to craft and use regular expressions to effectively search, match, and manipulate text.",
    topics: [
      "Basics of Regex",
      "Character Classes",
      "Quantifiers and Grouping",
      "Practical Examples",
    ],
    difficulty: "Beginner",
    image: require("../assets/img/Regex/Landing.jpg"),
    state: "semi-published",
    link: "/Regex",
  },
  {
    id: 17,
    category: "Vulnerabilities",
    title: "Cross-Site Scripting",
    description:
      "Learn the fundamentals of Cross-Site Scripting (XSS), one of the most common vulnerabilities in web applications.",
    topics: [
      "What is Cross-Site Scripting?",
      "Types of XSS",
      "Exploitation Techniques",
      "Mitigation Strategies",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/Cross_Site_Scripting/xss.jpeg.jpg"),
    state: "published",
    link: "/xss",
  },
  {
    id: 18,
    category: "Tools & Techniques",
    title: "wireshark",
    description:
      "Master the Fundamentals of Wireshark: A Powerful Tool for Cybersecurity and Code Protection",
    topics: [
      "Wireshark Overview",
      "Collection Methods",
      "ARP Traffic",
      "ICMP & TCP Traffic",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/wireshark/card_image.png"),
    state: "published",
    link: "/wireshark",
  },
  {
    id: 19,
    category: "Fundamentals",
    title: "Hashing",
    description:
      "Understand the principles of hashing, its applications in security, and how to implement secure hashing algorithms.",
    topics: [
      "Introduction to Hashing",
      "Common Hashing Algorithms",
      "Security Implications",
      "Best Practices",
    ],
    difficulty: "Beginner",
    image: require("../assets/img/Hashing/landing.jpg"),
    state: "published",
    link: "/Hashing",
  },
  {
    id: 20,
    category: "Vulnerabilities",
    title: "Command Injection",
    description:
      "Command injection allows attackers to execute arbitrary commands on a system due to improper input handling.",
    topics: [
      "Understanding Command Injection",
      "Networking Weaknesses",
      "Common Web Attacks",
      "Using the Linux OS",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/Command Injection/Content_Command_Injection.jpg"),
    state: "published",
    link: "/Command_Injection",
  },
  {
    id: 21,
    category: "Vulnerabilities",
    title: "File Inclusion",
    description:
      "Learn how file inclusion vulnerabilities like LFI and RFI are exploited. Understand their risks and explore remediation techniques to secure applications.",
    topics: [
      "Path Traversal",
      "Local File Inclusion (LFI)",
      "Remote File Inclusion (RFI)",
      "Remediation",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/File Inclusion/card_image.png"),
    state: "pending",
    link: "/fileinclusion",
  },
  {
    id: 22,
    category: "Fundamentals",
    title: "Digital Forensics",
    description:
      "Gain insights into digital forensics techniques and learn how to investigate and analyze digital evidence.",
    topics: [
      "Introduction to Digital Forensics",
      "Evidence Collection",
      "Analysis Techniques",
      "Case Studies",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/AudFor/landing.png"),
    state: "semi-published",
    link: "/Digital_Forensics",
  },
  {
    id: 23,
    category: "Vulnerabilities",
    title: "Insecure Deserialization",
    description:
      "Insecure deserialization happens when untrusted data is deserialized without proper validation, leading to potential attacks like code execution and data tampering.",
    topics: [
      "Serialization and Deserialization",
      "Remote Code Execution (RCE)",
      "Data Tampering Techniques",
      "Preventing Insecure Deserialization",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/Insecure_Deserialization/Content_Insecure_Photo.jpg"),
    state: "published",
    link: "/Insecure_Deserialization",
  },
  {
    id: 24,
    category: "Vulnerabilities",
    title: "Server Side Template Injection (SSTI)",
    description:
      "Server Side Template Injection (SSTI) is a vulnerability that occurs when user input is incorrectly embedded in server-side templates. Attackers can inject malicious code leading to security risks.",
    topics: [
      "Introduction",
      "SSTI Vulnerabilities",
      "Constructing a SSTI Attack",
      "Prevention Strategies",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/Server Side Template Injection/card_image.png"),
    state: "not-published",
    link: "/SSTI",
  },
  {
    id: 25,
    category: "Tools & Techniques",
    title: "API Hacking & Testing",
    description:
      "Learn how to assess the security of APIs through hands-on hacking and testing methodologies.",
    topics: [
      "API Fundamentals",
      "Common Vulnerabilities",
      "Testing Tools",
      "Mitigation Strategies",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/Api_Hacking/landing.png"),
    state: "pending",
    link: "/Api_Hacking",
  },
  {
    id: 26,
    category: "Fundamentals",
    title: "Temp Subject",
    description:
      "This is a placeholder course subject intended for upcoming content.",
    topics: ["Topic 1", "Topic 2", "Topic 3", "Topic 4"],
    difficulty: "Beginner",
    image: require("../assets/img/Lab2.jpg"),
    state: "not-published",
    link: "/infoDisc",
  },
  {
    id: 27,
    category: "Vulnerabilities",
    title: "Captcha Bypass",
    description:
      "Learn how captcha bypass techniques are used by attackers and explore ways to strengthen captcha implementations.",
    topics: [
      "Introduction to Captcha",
      "Bypass Techniques",
      "Real-world Examples",
      "Prevention Strategies",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/Captcha Bypass/card_image.png"),
    state: "not-published",
    link: "/captchabypass",
  },
  {
    id: 28,
    category: "Vulnerabilities",
    title: "click jacking",
    description:
      "Understand click jacking attacks and learn how to protect web applications against them.",
    topics: [
      "What is Click Jacking?",
      "Attack Techniques",
      "Prevention Methods",
      "Case Studies",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/Click_Jacking/landing.jpg"),
    state: "pending",
    link: "/Click_Jacking",
  },
  {
    id: 29,
    category: "Fundamentals",
    title: "Temp Subject",
    description:
      "This placeholder course will be updated with relevant content soon.",
    topics: ["Topic 1", "Topic 2", "Topic 3", "Topic 4"],
    difficulty: "Beginner",
    image: require("../assets/img/Lab2.jpg"),
    state: "not-published",
    link: "/infoDisc",
  },
  {
    id: 30,
    category: "Vulnerabilities",
    title: "JWT attacks",
    description:
      "Explore how JSON Web Tokens (JWT) can be exploited in attacks and learn strategies to secure token-based authentication.",
    topics: [
      "Introduction to JWT",
      "Common Attack Vectors",
      "Security Best Practices",
      "Mitigation Techniques",
    ],
    difficulty: "Intermediate",
    image: require("../assets/img/JWT attacks/card_image.png"),
    state: "not-published",
    link: "/jwtattacks",
  },
];

export default courseData;
