const courseData = [
  {
    id: 1,
    category: "Temporary Category",
    title: "Careers in Cyber",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/CareersInCyber/landing.jpg"),
    state: "pending",
    link: "/CareersInCyber",
  },
  {
    id: 2,
    category: "Web Vulnerabilities",
    title: "Cross-Site Scripting",
    description:
      "Learn the fundamentals of Cross-Site Scripting (XSS), one of the most common vulnerabilities in web applications.",
    topics: [
      "What is Cross-Site Scripting?",
      "Types of XSS",
      "Exploitation Techniques",
      "Mitigation Strategies",
    ],
    difficulty: "Easy",
    image: require("../assets/img/Cross_Site_Scripting/xss.jpeg.jpg"),
    state: "published",
    link: "/xss",
  },
  {
    id: 3,
    category: "Web Vulnerabilities",
    title: "Cookies",
    description:
      "Understand the role of cookies in web security, how they are used, and the potential privacy concerns they introduce.",
    topics: [
      "What Are Cookies?",
      "What are Cookies Used For?",
      "Where are Cookies Stored?",
      "Cookies Manipulation",
    ],
    difficulty: "Easy",
    image: require("../assets/img/cookies/Cookies_transparent.png"),
    state: "published",
    link: "/cookies",
  },
  {
    id: 4,
    category: "Web Vulnerabilities",
    title: "SQL Injection",
    description:
      "Learn how attackers exploit vulnerabilities in web applications using SQL injection and understand the techniques to detect and prevent them.",
    topics: [
      "Retrieving hidden data",
      "SQL injection UNION attacks",
      "Finding columns with a useful data type",
      "Using a SQL injection UNION attack to retrieve interesting data",
    ],
    difficulty: "Easy",
    image: require("../assets/img/SQL_Injection/landing3.png"),
    state: "published",
    link: "/sql_Injection",
  },
  {
    id: 5,
    category: "Server-Side Exploits",
    title: "Unrestricted File Upload",
    description:
      "Understand the risks and exploitation of unrestricted file upload vulnerabilities, a critical security issue in web applications.",
    topics: [
      "What is Unrestricted File Upload?",
      "Why is it Dangerous?",
      "Attack Techniques",
      "Exploitation Scenarios",
    ],
    difficulty: "Easy",
    image: require("../assets/img/Unrestricted File Upload/card_image.png"),
    state: "published",
    link: "/UnrestrictedFileUpload",
  },
  {
    id: 6,
    category: "Fundamentals",
    title: "Linux Fundamentals",
    description:
      "Build a solid foundation in Linux, the operating system at the core of many cybersecurity tools and infrastructures.",
    topics: [
      "Running Your First Few Commands",
      "Interacting with the Filesystem",
      "Searching for Files",
      "Introduction to Shell Operators",
    ],
    difficulty: "Easy",
    image: require("../assets/img/linux/linux_logo.png"),
    state: "published",
    link: "/linux",
  },
  {
    id: 7,
    category: "Web Vulnerabilities",
    title: "Access Control Vulnerabilities",
    description:
      "Learn how attackers exploit vulnerabilities in web applications to bypass access controls and understand the techniques to detect and prevent them.",
    topics: [
      "What are Access Control Vulnerabilities?",
      "Types of Access Control Flaws",
      "Exploitation Examples",
      "Mitigation Techniques",
    ],
    difficulty: "Easy",
    image: require("../assets/img/ACV/Landing.jpg"),
    state: "pending",
    link: "/AC_Vuln",
  },
  {
    id: 8,
    category: "Web Vulnerabilities",
    title: "Broken Authentication",
    description:
      "Broken authentication lets attackers impersonate users, leading to account takeovers and data breaches. Securing login and session management helps prevent these risks",
    topics: [
      "Weak Passwords",
      "Session Management Issues",
      "Lack of MFA",
      "Credential Stuffing",
    ],
    difficulty: "Easy",
    image: require("../assets/img/Broken Authentication/card_image.png"),
    state: "published",
    link: "/broken-auth",
  },
  {
    id: 9,
    category: "Server-Side Exploits",
    title: "Bash Scripting",
    description:
      " Master the basics of Bash scripting, a powerful tool for automating tasks and managing systems in cybersecurity environments.",
    topics: ["simple bash scripts", "Variables", "Parameters", "Arrays"],
    difficulty: "Easy",
    image: require("../assets/img/bash/bash_course_logo.png"),
    state: "published",
    link: "/bash-scripting",
  },
  {
    id: 10,
    category: "Web Vulnerabilities",
    title: "Business Logic Vulnerabilities",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Easy",
    image: require("../assets/img/BLV/Landing.jpg"),
    state: "not-published",
    link: "/BL_Vuln",
  },
  {
    id: 11,
    category: "Specialized Topics",
    title: "Insecure Direct Object Reference(IDOR)",
    description:
      "Delve into Insecure Direct Object Reference (IDOR) vulnerabilities, a common security issue in web applications. Learn how attackers exploit weak access controls to gain unauthorized access to sensitive resources.",
    topics: [
      "What is IDOR?",
      "Why is it Dangerous?",
      "Common Examples.",
      "Exploitation Techniques.",
      "Mitigation Strategies.",
    ],
    difficulty: "Easy",
    image: require("../assets/img/IDOR/Insecure_Direct_Object_Reference.png"),
    state: "published",
    link: "/Insecure_Direct_Object_Reference(IDOR)",
  },
  {
    id: 12,
    category: "Specialized Topics",
    title: "Obfuscation",
    description:
      "Master the basics of obfuscation, a powerful technique for securing code and protecting intellectual property in cybersecurity environments",
    topics: [
      "What are Obfuscation & Deobfuscation?",
      "Why do we use Obfuscation?",
      "Javascript Obfuscation",
      "JS Deobfuscation Tools",
    ],
    difficulty: "Easy",
    image: require("../assets/img/Obfuscation/card_image.png"),
    state: "published",
    link: "/obfuscation",
  },
  {
    id: 10,
    category: "Fundamentals",
    title: "Cross Site Request Forgery (CSRF)",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Easy",
    image: require("../assets/img/CSRF/landing.jpg"),
    state: "not-published",
    link: "/CSRF",
  },
  {
    id: 14,
    category: "Web Vulnerabilities",
    title: "Path Traversal",
    description:
      "xploiting file path vulnerabilities to access restricted directories and files.",
    topics: [
      "Path traversal techniques",
      "Directory traversal prevention",
      "Secure file access mechanisms",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Path__Traversal/Photo_Content_Path_Traversal.png"),
    state: "published",
    link: "/Path__Traversal",
  },
  {
    id: 15,
    category: "Temporary Category",
    title: "Cryptography",
    description:
      "Master the basics of CryptoGraphy, a powerful technique for securing code and protecting intellectual property in cybersecurity environments.",
    topics: [
      "What is Cryptography?",
      "What is Steganography?",
      "How does Steganography differ from Cryptography?",
      "Types of Encryption",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Cryptography/card_image.png"),
    state: "published",
    link: "/cryptography",
  },
  {
    id: 16,
    category: "Specialized Topics",
    title: "Regular expressions",
    description:
      " Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Easy",
    image: require("../assets/img/Regex/Landing.jpg"),
    state: "published",
    link: "/Regex",
  },
  {
    id: 17,
    category: "Temporary Category",
    title: "Burp Suite",
    description:
      " Learn the core skills required to start a career in cyber security",
    topics: [
      "Learn about different careers in cyber",
      "Hack your first application",
      "Defend against a live cyber attack",
      "Explore security topics in the industry",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Burp_Suit/BurpSuit_Content.png"),
    state: "not-published",
    link: "/Burp_Suit",
  },
  {
    id: 18,
    category: "Temporary Category",
    title: "wireshark",
    description:
      "Master the Fundamentals of Wireshark: A Powerful Tool for Cybersecurity and Code Protection",
    topics: [
      "Wireshark Overview",
      "Collection Methods",
      "ARP Traffic",
      "ICMP & TCP Traffic",
    ],
    difficulty: "Medium",
    image: require("../assets/img/wireshark/card_image.png"),
    state: "published",
    link: "/wireshark",
  },
  {
    id: 19,
    category: "Temporary Category",
    title: "Hashing",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Hashing/landing.jpg"),
    state: "published",
    link: "/Hashing",
  },
  {
    id: 20,
    category: "Web Vulnerabilities",
    title: "Command Injection",
    description:
      "Command injection allows attackers to execute arbitrary commands on a system due to improper input handling.",
    topics: [
      "Cyber Security Basics",
      "Networking Weaknesses",
      "Common Web Attacks",
      "Using the Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Command Injection/Content_Command_Injection.jpg"),
    state: "published",
    link: "/Command_Injection ",
  },
  {
    id: 21,
    category: "Temporary Category",
    title: "File Inclusion",
    description:
      "Learn how file inclusion vulnerabilities like LFI and RFI are exploited. Understand their risks and explore remediation techniques to secure applications",
    topics: [
      "Path Traversal",
      "Local File Inclusion (LFI)",
      "Remote File Inclusion (RFI)",
      "Remediation",
    ],
    difficulty: "Medium",
    image: require("../assets/img/File Inclusion/card_image.png"),
    state: "pending",
    link: "/fileinclusion",
  },
  {
    id: 22,
    category: "Temporary Category",
    title: "Digital Forensics",
    description:
      " Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/AudFor/landing.png"),
    state: "published",
    link: "/Digital_Forensics",
  },
  {
    id: 23,
    category: "Server-Side Exploits",
    title: "Insecure Deserialization",
    description:
      "Insecure deserialization happens when untrusted data is deserialized without proper validation, leading to potential attacks like code execution and data tampering.",
    topics: [
      "Serialization and Deserialization",
      "Remote Code Execution (RCE)",
      "Data Tampering Techniques",
      "Preventing Insecure Deserialization",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Insecure_Deserialization/Content_Insecure_Photo.jpg"),
    state: "pending",
    link: "/Insecure_Deserialization",
  },
  {
    id: 24,
    category: "Temporary Category",
    title: "Server Side Template Injection (SSTI)",
    description:
      "Server Side Template Injection (SSTI) is a vulnerability that occurs when user input is incorrectly embedded in server-side templates. Attackers can inject malicious code leading to  security risks.",
    topics: [
      "Introduction",
      "SSTI vulnerabilities",
      "Constructing a SSTI attack",
      "How to prevent SSTI vulnerabilities",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Server Side Template Injection/card_image.png"),
    state: "not-published",
    link: "/SSTI",
  },
  {
    id: 25,
    category: "Temporary Category",
    title: "API Hacking & Testing",
    description:
      " Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Api_Hacking/landing.png"),
    state: "pending",
    link: "/Api_Hacking",
  },
  {
    id: 26,
    category: "Temporary Category",
    title: "?????",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Lab2.jpg"),
    state: "not-published",
    link: "/infoDisc",
  },
  {
    id: 27,
    category: "Temporary Category",
    title: "Captcha Bypass",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Captcha Bypass/card_image.png"),
    state: "not-published",
    link: "/captchabypass",
  },
  {
    id: 28,
    category: "Temporary Category",
    title: "click jacking",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Click_Jacking/landing.jpg"),
    state: "pending",
    link: "/Click_Jacking",
  },
  {
    id: 29,
    category: "Temporary Category",
    title: "29.",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/Lab2.jpg"),
    state: "not-published",
    link: "/infoDisc",
  },
  {
    id: 30,
    category: "Temporary Category",
    title: "JWT attacks",
    description:
      "Before hacking something, you first need to understand the basics",
    topics: [
      "Cyber Security Basics",
      "Networking Basics and Weaknesses",
      "The Web And Common Attacks",
      "Learn to Use The Linux OS",
    ],
    difficulty: "Medium",
    image: require("../assets/img/JWT attacks/card_image.png"),
    state: "not-published",
    link: "/jwtattacks",
  },
];

export default courseData;
